### ISSUE TITLE
Sending two commands belonging to different aggregates does strange behaviour

### ISSUE THREAD

**Issue by juanluisdar** [AxonIQ/reference-guide#101]
Hi,
I have two aggregates with corresponding commands and events as documentation suggests. And the following configuration:
- Both aggregates are event sourced
- Axon Server as Event Store. 
- Jackson serializer

When I send 2 commands, one for each aggregate with commandGateway.send(), I have the following strange behaviour: Sometimes one event serializes ok, another times other one doesn't. Other times both events are ok serialized, and other, no event are serialized ok. So it seems a random behaviour.

I realize that when a command doesn't finish well, Axon don't use the aggregate constructor (I have a log trace and a breakpoint in that point) but data is in event store (but bad serialized anyway).

You can see a screenshot from my local axon server:

![Screenshot from 2019-11-21 17-52-59](https://user-images.githubusercontent.com/5428489/69359729-67d0a000-0c89-11ea-8909-b6d77d803395.png)

In this case the token 21 is the result expected (customerAggregate). The token 20, belonging to ScopeAggregate is unexpected serialized. But as I said before, the results are not equals.

All aggregates, commands and events are coded at same manner. what I have bad configured?

Thanks in advance.

**Comment by smcvb** [comment]
@juanluisdar, have a couple of pointers regarding your question here:

1. The issue tracker is intended for feature / enhancement requests or bugs. What you are asking, is more so a usage question. By default, we close issue likes these as it is intended to use any of the open channels like StackOverflow or the [Axon Usergroup](https://groups.google.com/forum/#!forum/axonframework), or better, [contact AxonIQ](https://axoniq.io/) directly.
2. You are stating you have flaky behavior from an event storage / serialization perspective. I would **always** expect dedicating logging statements or exceptions to pop up when something like this happens. Thus, once you drop this question on the aforementioned channels, you should add stack traces to specify what's failing. Thus, without the exact exception, we cannot help you correctly. 

Due to the nature of this ticket being a question, I will close it as is.
