### ISSUE TITLE
[3.4] Merge open branches to 3.4 reference guide

### ISSUE THREAD

**Issue by marleinevankampen** [AxonIQ/reference-guide#14]
Currently, the following branches are still in the AxonFramework/ReferenceGuide project and are copied over to this (AxonIQ/reference-guide) project.

The branches should be merged to the 3.4/master branch or should be deleted

- deadlines
- distribution-considerations
- feature/34
- feature/61

**Comment by marleinevankampen** [comment]
@m1l4n54v1c I assigned you to this ticket as it seems like you created (some of) these branches. 

I see there is a "Quick Start" introduced as well, which is really nice. I think we should include this in the reference guide.

**Comment by m1l4n54v1c** [comment]
@smcvb do you mind providing the info about `feature/34` and `feature/61` branches?

**Comment by smcvb** [comment]
Branch [#61](https://github.com/AxonFramework/ReferenceGuide/issues/61) is for the eBook work, which we've decided against. That branch can be removed, but I'd suggest keeping it around for now so that we have a reference of that work.

Branch [#34](https://github.com/AxonFramework/ReferenceGuide/issues/34) is a set of code samples, which I do believe is beneficial to add. I'll revert that one to point to 3.4 on the PR side of things and I'll start working on that again. Axon-4 got in the way of that.
