### ISSUE TITLE
Decribe Section 3.B: Event Handling

### ISSUE THREAD

**Issue by bert-laverman** [AxonIQ/reference-guide#34]
Provide a description on how to handle and dispatch `EventMessages` throughout an Axon application.

**Comment by smcvb** [comment]
All updates that occurred on the event handling section, most recently with pull request #210, provide a more thorough explanation in all.
Due to this, I believe this issue has been dealt with by now.

As such, I will close this issue as resolved. 
Feel free to provide comments if we should open it again.
