### ISSUE TITLE
Provide some example how to use RoutingKey

### ISSUE THREAD

**Issue by janesser** [AxonIQ/reference-guide#57]
The reference-guide is giving good intro. Keep it up! Good work!

One case that would benefit from further elaboration is the "routing-case":
When dealing with different application being connected to axon-server, i.e. axon4, or related use-case with axon3, how does RoutingStrategy apply.

What is \@RoutingKey matched with?
It is AxonServerConfig.component or AxonServerConfig.clientId?

In this case which piece of code is executed in which place?
The command is emitted in the application A.
AxonServer will route Command to application B.
In application B the code of the aggregate will be executed.
Triggered events will be persisted in the event-store which again resides in the AxonServer.

I have plenty of doubt's about this last paragraph. An extension to the guide would support deeper understanding of newcomers to the CQRS matter.

**Comment by smcvb** [comment]
I actually missed checking the outstanding issue, but I believe the predicament you describe here @janesser has been resolved.
More specifically by pull request #199.

This pull request introduced a dedicated section on the `RoutingStrategy`.
This section explains shortly what the `RoutingStrategy` is, which options the framework provides, when it is used, and why.
You can find the section [here](https://docs.axoniq.io/reference-guide/axon-framework/axon-framework-commands/infrastructure#routing-strategy) by the way.

Due to this, I feel we can close this issue as resolved.
If you think we're still missing some subjects on the matter, feel free to comment here.
